local M = {}

M.TILE_WIDTH_PX = 32
M.TILE_HEIGHT_PX = 32
M.VIEWPORT_WIDTH = 640
M.VIEWPORT_HEIGHT = 360
M.VIEWPORT_TILE_WIDTH = math.ceil(M.VIEWPORT_WIDTH/M.TILE_WIDTH_PX)
M.VIEWPORT_TILE_HEIGHT = math.ceil(M.VIEWPORT_HEIGHT/M.TILE_HEIGHT_PX)

M.PLAYER_ACCELERATION = 3500 
M.AIR_FRICTION = 0.35
M.PLAYER_FRICTION = 6
M.PLAYER_MAX_SPEED = 165
M.PLAYER_MAX_FALL_SPEED = 600

M.FRICTION = 1.4
M.GRAVITY = 1500
M.JUMP_ACCELERATION = 565--650

return M

