go.property("health",5)


local gop = require "utils.gop"
local mess = require "shared.mess"

function init(self)
	self.global = gop.get_properties()
end

function on_message(self, message_id, message, sender)
    if message_id == mess.msg_take_damage and self.global.protect ~= true then
    	print("take_damage")
    	self.health = self.health - message.damage
    	if self.health <= 0 then
    		msg.post(".", mess.msg_die)
    	else
    		msg.post(".", mess.msg_protect)
    	end
    end
end
